name: Build and Deploy Dioxus Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to push commits

      # Install Rust toolchain
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # Install cargo-binstall for precompiled CLI
      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      # Install the pinned Dioxus CLI version
      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli@0.6.3 -y

      # Build the Dioxus web site
      - name: Build Dioxus site
        run: dx bundle

      # Commit and push to gh-pages
      - name: Deploy to gh-pages
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          commit-message: "Deploy Dioxus site"
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
